In [7]:
import tensorflow as tf

Create a Tensor with random float values
tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.float32)
print("Tensor:\n", tensor.numpy())

# Compute sum, mean, and max
sum_tensor = tf.reduce_sum(tensor)
mean_tensor = tf.reduce_mean(tensor)
max_tensor = tf.reduce_max(tensor)

print("\nSum of tensor:", sum_tensor.numpy())
print("Mean of tensor:", mean_tensor.numpy())
print("Max of tensor:", max_tensor.numpy())

Create a 3D Tensor
tensor_3d = tf.random.uniform(shape=(3, 4, 5), minval=0, maxval=10, dtype=tf.float32)
print("\n3D Tensor:\n", tensor_3d.numpy())

# Access a specific element (Example: element at index [1,2,3])
specific_element = tensor_3d[1, 2, 3]
print("\nSpecific element at [1,2,3]:", specific_element.numpy())

# Access a 2D slice (Example: First matrix at index 0)
slice_2d = tensor_3d[0]
print("\n2D Slice (First matrix at index 0):\n", slice_2d.numpy())

# Access a 1D slice (Example: First row of the first matrix)
slice_1d = tensor_3d[0, 0]
print("\n1D Slice (First row of the first matrix):\n", slice_1d.numpy())


Tensor:
 [[9.526247  3.3492863 0.842365 ]
 [8.956013  2.418816  2.3804045]
 [8.859062  7.622187  4.2118635]]

Sum of tensor: 48.166245
Mean of tensor: 5.3518047
Max of tensor: 9.526247

3D Tensor:
 [[[0.17438173 6.4149942  8.2500305  0.17086625 8.57559   ]
  [6.9421816  8.50223    3.1829154  6.2467537  1.8281031 ]
  [9.527407   7.3042965  2.2102714  0.01465082 3.259368  ]
  [5.7097874  1.6915178  2.2120643  1.2064707  9.584976  ]]

 [[4.912548   1.045618   7.2023163  2.1296585  2.9449964 ]
  [8.707825   6.8506026  1.1906874  0.82010746 8.680489  ]
  [0.61639786 4.502933   8.460226   2.7079391  0.49345732]
  [9.080494   2.1694815  5.1500225  1.5047002  4.7375917 ]]

 [[1.5673125  8.258949   1.95966    7.3242006  3.7625313 ]
  [5.9334373  1.5520597  0.6793773  3.2891786  5.6391134 ]
  [8.796307   9.1511345  9.847906   2.1240568  6.61263   ]
  [1.27756    8.986479   3.4509945  4.7113347  8.82988   ]]]

Specific element at [1,2,3]: 2.7079391

2D Slice (First matrix at index 0):
 [[0.174381