In [2]:
import numpy as np

# Create a NumPy array with random float values and sort it in both ascending and descending order
array = np.random.rand(5)  # 1D array with 5 random float values

# Sort the array in ascending order
ascending = np.sort(array)

# Sort the array in descending order
descending = ascending[::-1]  # Reverse the sorted array to get descending order

print("Task 1: Sort the array")
print("Original array:", array)
print("Sorted in ascending order:", ascending)
print("Sorted in descending order:", descending)

# Create a 2x2 NumPy matrix. Calculate its transpose and inverse.
matrix = np.array([[1, 2], [3, 4]])

# Calculate its transpose
transpose = np.transpose(matrix)

# Calculate its inverse
inverse = np.linalg.inv(matrix)

print("\nTask 2: Matrix Transpose and Inverse")
print("Original matrix:\n", matrix)
print("Transpose of the matrix:\n", transpose)
print("Inverse of the matrix:\n", inverse)

# Create a 2D NumPy array and calculate the sum of each row, the mean of each column, and the standard deviation of the entire array.
array_2d = np.random.rand(4, 3)  # 4x3 matrix of random float values

# Calculate the sum of each row
sum_rows = np.sum(array_2d, axis=1)

# Calculate the mean of each column
mean_columns = np.mean(array_2d, axis=0)

# Calculate the standard deviation of the entire array
std_deviation = np.std(array_2d)

print("\nTask 3: 2D Array Calculations")
print("Original 2D array:\n", array_2d)
print("Sum of each row:", sum_rows)
print("Mean of each column:", mean_columns)
print("Standard deviation of the entire array:", std_deviation)

Task 1: Sort the array
Original array: [0.83482472 0.91022696 0.96234269 0.66690961 0.69160405]
Sorted in ascending order: [0.66690961 0.69160405 0.83482472 0.91022696 0.96234269]
Sorted in descending order: [0.96234269 0.91022696 0.83482472 0.69160405 0.66690961]

Task 2: Matrix Transpose and Inverse
Original matrix:
 [[1 2]
 [3 4]]
Transpose of the matrix:
 [[1 3]
 [2 4]]
Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Task 3: 2D Array Calculations
Original 2D array:
 [[0.21284154 0.87604471 0.17653471]
 [0.64113773 0.5287063  0.68109013]
 [0.78375538 0.61420411 0.92119739]
 [0.83229966 0.44263361 0.47999276]]
Sum of each row: [1.26542096 1.85093415 2.31915688 1.75492602]
Mean of each column: [0.61750858 0.61539718 0.56470375]
Standard deviation of the entire array: 0.2325623412195338
