In [1]:
import tensorflow as tf

# Define the tensor_operations function
def tensor_operations(tensor1, tensor2):
    # Perform arithmetic operations
    addition = tensor1 + tensor2
    subtraction = tensor1 - tensor2
    multiplication = tensor1 * tensor2
    division = tensor1 / tensor2
    
    # Store results in a dictionary
    result = {
        "addition": addition,
        "subtraction": subtraction,
        "multiplication": multiplication,
        "division": division
    }
    
    return result

# Test the function with the provided tensors
tensor1 = tf.constant([10, 20, 30], dtype=tf.float32)
tensor2 = tf.constant([5, 10, 15], dtype=tf.float32)

# Get the result of the operations
results = tensor_operations(tensor1, tensor2)

# Print the results
for operation, result in results.items():
    print(f"{operation.capitalize()}:\n", result.numpy())

Addition:
 [15. 30. 45.]
Subtraction:
 [ 5. 10. 15.]
Multiplication:
 [ 50. 200. 450.]
Division:
 [2. 2. 2.]
